image: openjdk:8-jdk-alpine
pipelines:
  default:
    - step:
        name: Build and publish docker image.
        services:
          - docker
        script:
          - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
          - docker build -t bishal1503/library-service:latest .
          - docker push bishal1503/library-service:latest
    - step:
        name: Deploy to ECS
        script:
          # Replace the docker image name in the task definition with the newly pushed image.
          - export IMAGE_NAME="${DOCKERHUB_USERNAME}/library-service:latest"
          - envsubst < task-definition-template.json >  task-definition.json

          # Update the task definition.
          - pipe: atlassian/aws-ecs-deploy:1.0.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              CLUSTER_NAME: 'default'
              SERVICE_NAME: 'sample-app-service'
              TASK_DEFINITION: 'task-definition.json'
